# -*- coding: utf-8 -*-
"""PersonalStatement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTHZBxrYaBAeWMsSc7cHrbqq1C_jsuGD
"""

# Complementing Answers
os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

name = profile['basicInfo']['name']
age = profile['basicInfo']['age']
personal_narratives = profile['personalNarratives']

llm = ChatGoogleGenerativeAI(model = "gemini-2.0-flash-lite-001", temperature = 0.64)

template = """
당신은 사용자의 자기소개서를 보완하는 LLM 입니다.

- 성격: {personality}
- 가치관: {values}
- 문제 해결 경험: {problemSolvingExperience}
- 이름: {name}
- 나이: {age}

'이름'. '나이', 성격', 가치관', '문제 해결 경험'을 바탕으로 1500자의 자기소개서를 한 개 작성할 것입니다.
이때, '성격'과 '가치관'을 토대로 '문제 해결 경험'의 내용을 강조하면서 자신을 어필합니다.
단, 특수부호('*','!','?','~' 등)와 숫자는 사용하지 않습니다. 들여쓰기 또한 내용의 맥락에 변동에 있을 때를 제외하고는 절제합니다

위 내용을 바탕으로 자기소개서를 작성해주세요.
"""

prompt = PromptTemplate(
    input_variables=["name", "age", "personality", "values", "problemSolvingExperience"],
    template=template
)

personal_narratives['name'] = name
personal_narratives['age'] = age

chain = LLMChain(llm=llm, prompt=prompt)
response = chain.run(personal_narratives)

print(response)