# -*- coding: utf-8 -*-
"""ProfileQuestioning.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTHZBxrYaBAeWMsSc7cHrbqq1C_jsuGD
"""

# pip install langchain_google_genai google-generativeai --> should be installed
from google.cloud import aiplatform
from google.colab import auth
import vertexai
from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_core.prompts import PromptTemplate
from langchain.chains import LLMChain
from google.colab import userdata
import os


auth.authenticate_user()

# setting Gemini
project_id = 'rare-citadel-465906-g2'
!gcloud config set project {project_id}
vertexai.init(project=project_id, location='us-central1')


# filling profile by questioning
# Question 1

print("안녕하세요! 만나서 반가워요! 😊","혼자서는 작성하기 꺼렸던 자소서, 같이 만들어봐요 😆")
print("먼저, 본인의 개인 프로필을 작성해보려고 해요!")
print()

print("1. 귀하의 이름은 무엇입니까?")
profile["basicInfo"]["name"] = input("입력 : ")
print()

print("2. 귀하의 나이는 몇 살입니까?")
profile["basicInfo"]["age"] = input("입력 : ")
print()

print("3. 귀하의 성별은 무엇입니까? [ 남성 / 여성 ]")
profile["basicInfo"]["gender"] = input("입력 : ")
print()

print("4. 귀하의 이메일은 무엇입니까?")
profile["basicInfo"]["email"] = input("입력 : ")
print()

print("5. 귀하의 전화번호는 무엇입니까?")
profile["basicInfo"]["phone"] = input("입력 : ")

# Question 2 (Method 1)

print("좋아요!","이제 당신에 대해 더 깊이 알아보려고 해요!")
print()

t = ""

print("1-1. 귀하의 장점들 중 3개를 자유롭게 문장 형식으로 작성해주세요 :)")
t += "장점: "
t = input("입력 : ")
print()

print("1-2. 귀하의 단점 또한 3개를 골라 자유롭게 문장 형식으로 작성해주세요")
t += ", 단점: "
t += input("입력 : ")
profile["personalNarratives"]["personality"] = t
print()

print("2. 귀하께서 갖고 계신 인생관, 혹은 평소에 생각하고 계신 것이 있나요?")
profile["personalNarratives"]["values"] = input("입력 : ")
print()

print("3. 가장 중요한 질문입니다. 귀하의 문제해결능력이 드러나는 사례를 자유롭게 서술해주십시오.")
profile["personalNarratives"]["problemSolvingExperience"] = input("입력 : ")
print()

# modifing questions with insufficient answers
# Complementing Answers

os.environ["GOOGLE_API_KEY"] = userdata.get('GOOGLE_API_KEY')

llm = ChatGoogleGenerativeAI(model = "gemini-2.0-flash-lite-001", temperature = 0.64)

template = """
당신은 사용자의 자기소개서를 보완하는 LLM 입니다.

항목 이름: {field_name}
사용자의 현재 응답: {user_response}

전달받은 '항목 이름'과 '사용자의 현재 응답'을 먼저 출력해주세요.

그 후, 보완해야하는 프로필의 조건은 아래와 같습니다.
1. '항목 이름'과 '사용자의 현재 응답'의 문맥이 어울리지 않다고 판단할 때
2. '항목 이름'이 name, age, gender, email, phone이 아닐때, '사용자의 현재 응답'이 15자 아래일 때

조건에 해당될 시, 적절한 답변을 유도할 수 있도록 보완된 구체적인 후속 질문을 3가지씩 생성하십시오.
(단, 예시는 들지 말고, '항목 이름'에 대한 옳은 답변을 사용자로부터 얻어낼 수 있는 질문을 만듭니다)
"""

prompt = PromptTemplate(
    input_variables = ["field_name", "user_response"], # giving LLM 2 elements (field_name : 항목이름, user_response : 사용자의 현재 응답)
    template = template
)

chain = LLMChain(llm = llm, prompt = prompt)


def bump(value : str | None) -> bool: # to judge answer's inadequation
  if value is None:
    return True
  if len(value.strip()) < 15: # short description
    return True
  return False

def generate_question(profile: dict) -> dict:
  questions = {}
  for category, fields in profile.items():
    for field, value in fields.items():
      if bump(value) and category != 'basicInfo':
        print("**********************************",field, value,"**********************************")
        question = chain.run({
            "field_name" : field,
            "user_response" : value if value is not None else "None" # value가 None일 경우 "None" 문자열 전달
        })
        questions[f"{category}.{field}"] = question

  return questions


added_q = generate_question(profile)

# answering the modified questions
for k, q in added_q.items():
  print(f"[{k}] 추가 질문 : {q}")
  a1, a2 = k.split('.')
  profile[a1][a2] = input("입력 : ")
  print()

  #print("--> 생성된 질문")