# -*- coding: utf-8 -*-
"""PersonalStatement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTHZBxrYaBAeWMsSc7cHrbqq1C_jsuGD
"""

import nest_asyncio
from pyngrok import ngrok
import uvicorn
from pydantic import BaseModel

# prevent asyncio overlapping error
nest_asyncio.apply()

# create public URL by ngrok
public_url = ngrok.connect(8000)
print(f"🚀 FastAPI 앱이 실행 중입니다: {public_url}")

# Execute server by Uvicorn
uvicorn.run(app, host="0.0.0.0", port=8000)