# -*- coding: utf-8 -*-
"""PersonalStatement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTHZBxrYaBAeWMsSc7cHrbqq1C_jsuGD
"""

!ngrok config add-authtoken 2zoX5gXLRYWdhuVpT8xAKQsWfFJ_4cP7cKH8PHCNEiMHW7VwS

# Settinig Endpoints for URL

from fastapi import FastAPI, UploadFile, File # Flie
from fastapi.responses import HTMLResponse, FileResponse # url revising
from pydantic import BaseModel
import json
import os

app = FastAPI()
stored_text = {}
json_data = None
content = None

# Defining Class Types
# ===========================================================================
class InputData(BaseModel):
    name: str
    age: int

class TextData(BaseModel):
    text: str

class Item(BaseModel):
    name: str
    age: int
    Major: str

# ===========================================================================


# Defining Post Endpoints
# ===========================================================================

@app.post("/submit")
def receive_text(data: TextData):
    stored_text["text"] = data.text
    return {"message": f"Text Received! 입력된 텍스트: {data.text}"}

@app.post("/uploadfile/")
async def create_upload_file(file: UploadFile = File(...)):
    global stored_text

    if file.content_type != "application/json":
        return {"error": "Only JSON files are allowed"}

    content = await file.read()

    try:
        json_data = json.loads(content) #convert json into dict
        stored_text = json_data

    except json.JSON.loads(content):
        return {"error": "Invalid JSON content"}

    return {"filename": file.filename, "content": json_data}

# ===========================================================================


# Defining Get Endpoints
# ===========================================================================

@app.get("/get")
def sent_text():
    return {"text": stored_text["text"]}

@app.get("/get-json/")
async def download_json():
    global stored_text

    if not stored_text:
        return {"error": "File not found, is it updated?"}

    #return FileResponse(path = file_path, filename="my_data.json", media_type = "application/json")
    return stored_text

# ===========================================================================