# -*- coding: utf-8 -*-
"""PersonalStatement.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OTHZBxrYaBAeWMsSc7cHrbqq1C_jsuGD
"""

from types import resolve_bases
import requests, os
import json

url = "https://0efc0f756417.ngrok-free.app/"
url2 = url + "uploadfile/"
url3 = url + "get-json/"

address = "/content/people_data.json"
file_name = address.strip("/content/") # os.path.basename() --> file name

with open(address, "rb") as f:
    files = {
        'file': (file_name, f, "application/json")
    }
    response = requests.post(url2, files=files)
    print(response.json())

response2 = json.loads(response.text)
main_profile = response2['content'][0]
print(type(str(main_profile)))

response3 = requests.get(url3)
response3 = json.loads(response3.text)
print(response3[0])

main_profile = response3[0]